version: "3"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: oxelixo
       POSTGRES_DB: oxelixo
     ports:
       - 8082:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data
